         
% Programmed by: Aahan Singh Charak
%                aahancharak@gmail.com

function [ c_out ] = axpy_unb( alpha, b, c )

  [ bT, ...
    bB ] = FLA_Part_2x1( b, ...
                         0, 'FLA_TOP' );

  [ cT, ...
    cB ] = FLA_Part_2x1( c, ...
                         0, 'FLA_TOP' );

  while ( size( bT, 1 ) < size( b, 1 ) )

    [ b0, ...
      beta1, ...
      b2 ] = FLA_Repart_2x1_to_3x1( bT, ...
                                    bB, ...
                                    1, 'FLA_BOTTOM' );

    [ c0, ...
      gamma1, ...
      c2 ] = FLA_Repart_2x1_to_3x1( cT, ...
                                    cB, ...
                                    1, 'FLA_BOTTOM' );

    gamma1 = alpha*beta1+gamma1;

    [ bT, ...
      bB ] = FLA_Cont_with_3x1_to_2x1( b0, ...
                                       beta1, ...
                                       b2, ...
                                       'FLA_TOP' );

    [ cT, ...
      cB ] = FLA_Cont_with_3x1_to_2x1( c0, ...
                                       gamma1, ...
                                       c2, ...
                                       'FLA_TOP' );

  end

  c_out = [ cT
            cB ];

return
